python my_run_mlp.py < _config/config1.txt 1> result/result1.txt
python my_run_mlp.py < _config/config2.txt 1> result/result2.txt
python my_run_mlp.py < _config/config3.txt 1> result/result3.txt
python my_run_mlp.py < _config/config4.txt 1> result/result4.txt
python my_run_mlp.py < _config/config5.txt 1> result/result5.txt
python my_run_mlp.py < _config/config6.txt 1> result/result6.txt
python my_run_mlp.py < _config/config7.txt 1> result/result7.txt
python my_run_mlp.py < _config/config8.txt 1> result/result8.txt
python my_run_mlp.py < _config/config9.txt 1> result/result9.txt
python my_run_mlp.py < _config/config10.txt 1> result/result10.txt
python my_run_mlp.py < _config/config11.txt 1> result/result11.txt
python my_run_mlp.py < _config/config12.txt 1> result/result12.txt
python my_run_mlp.py < _config/config13.txt 1> result/result13.txt
python my_run_mlp.py < _config/config14.txt 1> result/result14.txt
python my_run_mlp.py < _config/config15.txt 1> result/result15.txt
python my_run_mlp.py < _config/config16.txt 1> result/result16.txt
python my_run_mlp.py < _config/config17.txt 1> result/result17.txt
python my_run_mlp.py < _config/config18.txt 1> result/result18.txt
python my_run_mlp.py < _config/config19.txt 1> result/result19.txt
